hacker-news/config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :users, only: [:new, :create]

  resources :posts do
    resources :postvotes, only: [:create, :destroy] do
      collection do
        post 'upvote'
        post 'downvote'
      end
    end
      resources :comments, only: [:new, :create, :destroy]
  end

  resources :comments, only: [:new, :create, :destroy] do
    resources :commentvote, only: [:create, :destroy]
  end

get '/register', to: 'users#new'
get '/login', to: 'users#get_login'
post '/login', to: 'users#login'
get '/signout', to: 'users#signout'

end

hacker-news/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  has_many :comment_votes
  validates :body, presence: true
  validates :user_id, presence: true

  def vote_count
    vote_object = CommentVote.where(comment_id: self.id)
    total_count = vote_object.reduce(0){|sum, n| sum + n.total}
  end
end

hacker-news/app/models/comment_vote.rb
class CommentVote < ActiveRecord::Base
  belongs_to :comment
  belongs_to :user
end

hacker-news/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_many :post_votes
  belongs_to :user
  validates :title, presence: true
  validates :user_id, presence: true

  def vote_count
    vote_object = PostVote.where(post_id: self.id)
    total_count = vote_object.reduce(0){|sum, n| sum + n.total}
  end

end

hacker-news/app/models/post_vote.rb
class PostVote < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

hacker-news/app/models/user.rb
class User < ActiveRecord::Base
  has_many :post_votes
  has_many :comment_votes
  has_many :posts
  has_many :comments
  validates :username, presence: true, uniqueness: true
  has_secure_password

  def post_voted?(post)
    post.post_votes.pluck(:user_id).include?(self.id)
  end

  def comment_voted?(comment)
    comment.comment_votes.pluck(:user_id).include?(self.id)
  end

end

hacker-news/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user != nil
  end
end

hacker-news/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    post = Post.find(params[:post_id])
    @comment = Comment.where(post_id: post.id)
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    if @comment.save
      redirect_to "/posts/#{params[:post_id]}"
    else
      render :new
    end
  end

  def destroy
    @comment= Comment.find(params[:id])
    @comment.destroy
    redirect_to "/posts/#{params[:post_id]}"
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

hacker-news/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = session[:user_id]
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to @post
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
  end
  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

hacker-news/app/controllers/postvotes_controller.rb
class PostvotesController < ApplicationController
  def upvote
    @post = Post.find(params[:post_id])
    if logged_in? && !current_user.post_voted?(@post)
      flash.now[:alert]= "You already voted"
    end
    @post.post_votes.create(total: 1, user: current_user)
    redirect_to root_path
  end

  def downvote
    @post = Post.find(params[:post_id])
    if current_user.post_voted?(@post)
      flash.now[:alert]= "You already voted"
    end
    @post.post_votes.create(total: -1, user: current_user)
    redirect_to root_path
  end




end

hacker-news/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :register
    end
  end

  def get_login
    @user = User.new
  end

  def login
    user = User.find_by(username: params[:user][:username])
    if user&& user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to '/get_login'
    end
  end

  def signout
    session.clear
    redirect_to root_path
  end


  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

hacker-news/app/helpers/application_helper.rb
module ApplicationHelper
end

hacker-news/app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <fieldset>
    <legend>Post Details: </legend>
  <% [:body].each do |field| %>
  <div>
    <%= f.label field %>
    <%= f.text_field field %>
  </div>
  <% end %>
    <%= f.submit %>
  </fieldset>
<% end %>

hacker-news/app/views/comments/new.html.erb
<%= render partial: 'form' %>

hacker-news/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Home", '/' %>
<% if logged_in? %>
  <p>Hello <%= current_user.username %></p>
  <p><%= link_to "SignOut", '/signout' %></p>
<% else %>
  <p><%= link_to "Register", '/register' %></p>
  <p><%= link_to "Log-In", '/login' %></p>
<% end %>
<h1>Welcome to the fake Hackernews</h1>

<%= yield %>

</body>
</html>

hacker-news/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<fieldset>
  <legend>Post Details: </legend>
<% [:title, :body].each do |field| %>
<div>
  <%= f.label field %>
  <%= f.text_field field %>
</div>
<% end %>
  <%= f.submit %>

</fieldset>
<% end %>

hacker-news/app/views/posts/edit.html.erb
<h3>Edit or Delete this Post</h3>

<%= render partial: 'form'%>


<%= button_to "Delete post", post_path, method: :delete %>

hacker-news/app/views/posts/index.html.erb
<% if logged_in?  %>
  <%= link_to "Create New Post", '/posts/new'%>
<% end %>
<hr>
<% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %> posted by <%=post.user.username%> with <%= post.vote_count %> votes</li>
  <% if logged_in?  %>
    <%= link_to "Upvote", upvote_post_postvotes_path(post), method: :post %>
    <%= link_to "Downvote", downvote_post_postvotes_path(post), method: :post%>
  <% end %>
  <br>
<% end %>

hacker-news/app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%= render partial: 'form'%>

hacker-news/app/views/posts/show.html.erb
<h2>Post Title:</h2>
<h4> <%= @post.title %> </h4>
<h3>Post body: </h3>
<h4>  <%= @post.body %></h4>
<% if @post.user_id == session[:user_id] %>
  <button><%= link_to "Modify this post", edit_post_path %></button>
<% end %>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p><%= comment.body %></p>
  <p>commented by: <%=comment.user.username%> with <%= comment.vote_count %> votes</p>
    <% if session[:user_id] == comment.user_id %>
     <%= button_to "Delete this comment", post_comment_path(comment.post,comment), method: :delete %>
    <% end %>
<% end %>

<% if logged_in? %>
  <%= link_to "Post a comment on this post", new_post_comment_path(@post)%>
<% end %>

hacker-news/app/views/users/get_login.html.erb
<h1>Login</h1>
<%= form_for @user, url: {action: 'login'} do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Login" %>

<% end %>

hacker-news/app/views/users/new.html.erb
<h1>Register</h1>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Register" %>
<% end %>